apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xwiki-additional-pvc
spec:
  accessModes:
    - ReadWriteMany
  #storageClassName: local-path
  resources:
    requests:
      storage: 5Gi  # Adjust the size as needed
